<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NothingVpn.Application\NothingVpn.Application.csproj" />
    <ProjectReference Include="..\NothingVpn.Domain\NothingVpn.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\NothingVpn.Tray\Internal\**\*.cs" Link="Legacy\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
